version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: 'gr-rabbitmq'
    hostname: 'gr-rabbit'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./data/rabbitmq/data/:/var/lib/rabbitmq/
        - ./data/rabbitmq/log/:/var/log/rabbitmq/
