# Generated by Django 3.2.23 on 2023-12-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'Euros'), ('EUR', 'Dollars')], default='USD', max_length=4),
        ),
    ]
