# Generated by Django 3.2.23 on 2023-12-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', '$ United States dollar'), ('eur', '€ Euro')], default='usd', max_length=4),
        ),
    ]
